### ISSUE TITLE
プラグインが自動読み込みされない

### ISSUE THREAD

**Issue by shimoe** [WRS-TNK/choreonoid_ros_pkg#2]
最新版choreonoidと一緒にビルドしたとき，choreonoid起動時にプラグインが読み込まれません
問題のプラグイン自体のファイル名は```RosBodyPlugin```

```devel/lib/choleonoid-1.7/```の中に上記のプラグインファイルは存在しているのですが，起動時に読み込まれない状況です
choreonoid起動後にプラグインファイルを読み込むと問題なく読み込まれるのでプラグインそのものに問題はない様です．

**Comment by RyodoTanaka** [comment]
なるほど
つまりクリティカルな問題ではないが，Choreonoid Discuss に投稿すべき内容

**Comment by RyodoTanaka** [comment]
おそらく解決済み & 多分 catkin source し忘れなだけなので閉じます．
